//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concesionario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        public int id { get; set; }
        public string matricula { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public decimal coste { get; set; }
        public int tipo { get; set; }
    
        public virtual Tipo Tipo1 { get; set; }
    }
}
